n1=float(input("Enter first floating point number"))
n2=float(input("Enter first floating point number"))
print("Addition=",n1+n2)
print("Subtraction",n1-n2)
print("Multiplication",n1*n2)
print("Division",n1/n2)
print("Modulus",n1%n2)
print("Exponentiation",n1**n2)
print("Floor division",n1//n2)

